-- AlterTable
ALTER TABLE "User" ADD COLUMN "googleId" TEXT UNIQUE,
ADD COLUMN "phoneNumber" TEXT UNIQUE,
ADD COLUMN "isPhoneVerified" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL;