EnvironmentConfigurationMetadata:
  Description: Configuration created from the EB CLI using "eb config save".
  DateCreated: '1735934961000'
  DateModified: '1735934961000'
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:ap-south-1::platform/Node.js 22 running on
    64bit Amazon Linux 2023/6.4.1
OptionSettings:
  aws:elasticbeanstalk:command:
    BatchSize: '1'
    BatchSizeType: Fixed
    DeploymentPolicy: Rolling
  AWSEBSecurityGroup.aws:ec2:vpc:
    VPCId: vpc-07897cdf790304d9f
  AWSEBRDSDBSubnetGroup.aws:ec2:vpc:
    DBSubnets: subnet-04a175fc949163895
  AWSEBAutoScalingGroup.aws:ec2:vpc:
    Subnets: subnet-04a175fc949163895
  AWSEBAutoScalingLaunchConfiguration.aws:ec2:vpc:
    AssociatePublicIpAddress: false
  aws:rds:dbinstance:
    DBPassword: darpo_db_username_password
    HasCoupledDatabase: true
    DBUser: darpoUser
  AWSEBAutoScalingLaunchConfiguration.aws:autoscaling:launchconfiguration:
    SecurityGroups: sg-064013f77d9743d12
    RootVolumeSize: '10'
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
  aws:elasticbeanstalk:managedactions:
    ManagedActionsEnabled: true
    PreferredStartTime: SAT:05:06
  aws:elasticbeanstalk:managedactions:platformupdate:
    UpdateLevel: minor
  aws:ec2:instances:
    SpotFleetOnDemandAboveBasePercentage: '0'
  aws:elasticbeanstalk:environment:
    ServiceRole: arn:aws:iam::590184025903:role/aws-elasticbeanstalk-service-role
    EnvironmentType: SingleInstance
    LoadBalancerType: application
  aws:elasticbeanstalk:healthreporting:system:
    ConfigDocument:
      Version: 1
      CloudWatchMetrics:
        Instance:
          ApplicationRequests5xx: 60
          ApplicationRequests4xx: 60
        Environment:
          ApplicationLatencyP95: 60
      Rules:
        Environment:
          ELB:
            ELBRequests4xx:
              Enabled: true
          Application:
            ApplicationRequests4xx:
              Enabled: true
  aws:autoscaling:launchconfiguration:
    EC2KeyName: aws-eb
    RootVolumeType: gp2
  AWSEBRDSDatabase.aws:rds:dbinstance:
    DBEngineVersion: '16.3'
    DBAllocatedStorage: '10'
    DBInstanceClass: db.t3.small
    DBEngine: postgres
    MultiAZDatabase: false
    DBDeletionPolicy: Delete
EnvironmentTier:
  Type: Standard
  Name: WebServer
AWSConfigurationTemplateVersion: 1.1.0.0
